imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @UsersUsersBundle/Resources/config/admin.yml }
    - { resource: @UsersUsersBundle/Resources/config/patient.yml }
    - { resource: @UsersUsersBundle/Resources/config/chambre.yml }
    - { resource: @UsersUsersBundle/Resources/config/facture.yml }

framework:
    validation:
        enable_annotations: true
        api: 2.4 
        # default is auto which sets broken API 2.5
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"
            # Formatter options: compressed, lessjs, classic
            formatter: "compressed"
            preserve_comments: false
            presets:
                my_variable: "#000"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  
    transport: gmail
    username: a.h.hichem@gmail.com
    password: h.hichem@1989
    disable_delivery: false
    spool: { type: memory }
    
    # app/config/config.yml
fos_user:
    db_driver: orm 
   
    # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Users\UsersBundle\Entity\Users
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:        registration@Hoptalplus.com
        sender_name:    hopital plus Registration
    registration:
        confirmation:
            enabled:    true
     


        
sonata_admin:
    templates:
        # other configuration options
        layout: UsersUsersBundle::standard_layout.html.twig
       
    title:      Hopital+  administration
    title_logo: bundles/UsersUsers/images/hopit.jpg
       
       
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
          
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Bienvenu dans le system administratif</h2>
                        <p>i5dim 3ala rouhik <code>ma5ir tbalfit</code>
       
   
#pour cree des costume bloks :) a5atf barka 
sonata_block:
  
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:
        
        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:
        
