users_users:
    resource: "@UsersUsersBundle/Resources/config/routing.yml"
    prefix:   /
medecin_i:
    resource: "@MedecinIBundle/Resources/config/routing.yml"
    prefix:   /
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
facture:
    resource: "@FactureBundle/Resources/config/routing.yml"
    prefix:   /  
mail:
  resource: "@mailBundle/Resources/config/routing.yml"
  prefix:   /