rendezvous:
    path:     /
    defaults: { _controller: "MedecinIBundle:Rendezvous:index" }

rendezvous_show:
    path:     /{id}/show
    defaults: { _controller: "MedecinIBundle:Rendezvous:show" }

rendezvous_new:
    path:     /new
    defaults: { _controller: "MedecinIBundle:Rendezvous:new" }

rendezvous_create:
    path:     /create
    defaults: { _controller: "MedecinIBundle:Rendezvous:create" }
    methods:  POST

rendezvous_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedecinIBundle:Rendezvous:edit" }

rendezvous_update:
    path:     /{id}/update
    defaults: { _controller: "MedecinIBundle:Rendezvous:update" }
    methods:  [POST, PUT]

rendezvous_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedecinIBundle:Rendezvous:delete" }
    methods:  [POST, DELETE]
rendezvous_accepte:
    path:     /{code}/accept
    defaults: { _controller: "MedecinIBundle:Rendezvous:accepterrdv" }
rendezvous_refuse:
    path:     /{code}/refuse
    defaults: { _controller: "MedecinIBundle:Rendezvous:refuserrdv" }   