<?php

namespace Proxies\__CG__\Users\UsersBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Facture extends \Users\UsersBundle\Entity\Facture implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'idfacture', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'prixConsultation', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'prixChambre', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'prixTrait', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'prixExamLabo', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'prixTotal', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'dateFacture', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'idpatient');
        }

        return array('__isInitialized__', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'idfacture', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'prixConsultation', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'prixChambre', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'prixTrait', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'prixExamLabo', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'prixTotal', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'dateFacture', '' . "\0" . 'Users\\UsersBundle\\Entity\\Facture' . "\0" . 'idpatient');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Facture $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdfacture()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdfacture();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfacture', array());

        return parent::getIdfacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixConsultation($prixConsultation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixConsultation', array($prixConsultation));

        return parent::setPrixConsultation($prixConsultation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixConsultation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixConsultation', array());

        return parent::getPrixConsultation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixChambre($prixChambre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixChambre', array($prixChambre));

        return parent::setPrixChambre($prixChambre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixChambre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixChambre', array());

        return parent::getPrixChambre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixTrait($prixTrait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixTrait', array($prixTrait));

        return parent::setPrixTrait($prixTrait);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixTrait()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixTrait', array());

        return parent::getPrixTrait();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixExamLabo($prixExamLabo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixExamLabo', array($prixExamLabo));

        return parent::setPrixExamLabo($prixExamLabo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixExamLabo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixExamLabo', array());

        return parent::getPrixExamLabo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixTotal($prixTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixTotal', array($prixTotal));

        return parent::setPrixTotal($prixTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixTotal', array());

        return parent::getPrixTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFacture($dateFacture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFacture', array($dateFacture));

        return parent::setDateFacture($dateFacture);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFacture', array());

        return parent::getDateFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpatient(\Users\UsersBundle\Entity\Patient $idpatient = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpatient', array($idpatient));

        return parent::setIdpatient($idpatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpatient', array());

        return parent::getIdpatient();
    }

}
