<?php

namespace Proxies\__CG__\Users\UsersBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dossiermedical extends \Users\UsersBundle\Entity\Dossiermedical implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Users\\UsersBundle\\Entity\\Dossiermedical' . "\0" . 'codedm', '' . "\0" . 'Users\\UsersBundle\\Entity\\Dossiermedical' . "\0" . 'datecreation', '' . "\0" . 'Users\\UsersBundle\\Entity\\Dossiermedical' . "\0" . 'codepatient', '' . "\0" . 'Users\\UsersBundle\\Entity\\Dossiermedical' . "\0" . 'codemedecin');
        }

        return array('__isInitialized__', '' . "\0" . 'Users\\UsersBundle\\Entity\\Dossiermedical' . "\0" . 'codedm', '' . "\0" . 'Users\\UsersBundle\\Entity\\Dossiermedical' . "\0" . 'datecreation', '' . "\0" . 'Users\\UsersBundle\\Entity\\Dossiermedical' . "\0" . 'codepatient', '' . "\0" . 'Users\\UsersBundle\\Entity\\Dossiermedical' . "\0" . 'codemedecin');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dossiermedical $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodedm()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCodedm();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodedm', array());

        return parent::getCodedm();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', array($datecreation));

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', array());

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodepatient($codepatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodepatient', array($codepatient));

        return parent::setCodepatient($codepatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodepatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodepatient', array());

        return parent::getCodepatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodemedecin($codemedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodemedecin', array($codemedecin));

        return parent::setCodemedecin($codemedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodemedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodemedecin', array());

        return parent::getCodemedecin();
    }

}
