<?php

namespace Proxies\__CG__\Users\UsersBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Rdvdisponible extends \Users\UsersBundle\Entity\Rdvdisponible implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Users\\UsersBundle\\Entity\\Rdvdisponible' . "\0" . 'numrd', '' . "\0" . 'Users\\UsersBundle\\Entity\\Rdvdisponible' . "\0" . 'cinm', '' . "\0" . 'Users\\UsersBundle\\Entity\\Rdvdisponible' . "\0" . 'dater', '' . "\0" . 'Users\\UsersBundle\\Entity\\Rdvdisponible' . "\0" . 'heurer', '' . "\0" . 'Users\\UsersBundle\\Entity\\Rdvdisponible' . "\0" . 'dispo');
        }

        return array('__isInitialized__', '' . "\0" . 'Users\\UsersBundle\\Entity\\Rdvdisponible' . "\0" . 'numrd', '' . "\0" . 'Users\\UsersBundle\\Entity\\Rdvdisponible' . "\0" . 'cinm', '' . "\0" . 'Users\\UsersBundle\\Entity\\Rdvdisponible' . "\0" . 'dater', '' . "\0" . 'Users\\UsersBundle\\Entity\\Rdvdisponible' . "\0" . 'heurer', '' . "\0" . 'Users\\UsersBundle\\Entity\\Rdvdisponible' . "\0" . 'dispo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Rdvdisponible $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNumrd()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNumrd();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumrd', array());

        return parent::getNumrd();
    }

    /**
     * {@inheritDoc}
     */
    public function setCinm($cinm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinm', array($cinm));

        return parent::setCinm($cinm);
    }

    /**
     * {@inheritDoc}
     */
    public function getCinm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinm', array());

        return parent::getCinm();
    }

    /**
     * {@inheritDoc}
     */
    public function setDater($dater)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDater', array($dater));

        return parent::setDater($dater);
    }

    /**
     * {@inheritDoc}
     */
    public function getDater()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDater', array());

        return parent::getDater();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeurer($heurer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeurer', array($heurer));

        return parent::setHeurer($heurer);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeurer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeurer', array());

        return parent::getHeurer();
    }

    /**
     * {@inheritDoc}
     */
    public function setDispo($dispo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDispo', array($dispo));

        return parent::setDispo($dispo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDispo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDispo', array());

        return parent::getDispo();
    }

}
