Fichepatient:
    type: entity
    table: fichepatient
    indexes:
        codeDm:
            columns:
                - codeDm
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        taille:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        poid:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        tension:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        temperature:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        perimetre:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        groupeSanguin:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: groupe_sanguin
        codedm:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: codeDm
        datecreation:
            type: date
            nullable: false
            comment: ''
            column: dateCreation
    lifecycleCallbacks: {  }
